title: Interpretive &ndash; Stop wasting time analysing your data and start selling more.
email: team@interpretive.io
description: Stop wasting time analysing your data and start selling more.
baseurl: ""
url: "//www.interpretive.io"
app_url: "//app.interpretive.io"
google_analytics: 123

linkedin_username: interpretive
twitter_username: theinterpretive
github_username:  interpretive

# Build settings
markdown: kramdown
