# Site settings
title: Interpretive &ndash; Stop wasting time analyising your data and start selling more.
email: your-email@domain.com
description: Stop wasting time analyising your data and start selling more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "//www.interpretive.io" # the base hostname & protocol for your site
twitter_username: interpretiveapp
github_username:  interpretive

# Build settings
markdown: kramdown
